deploy_binary:
	echo "This should build the binary that runs the service. "\
	"Note that the binary will not necessarily run on the machine that builds it. "\
	"Also notes that you don't have to use make for this, feel free to use any "\
	"build rule system..."
